// <auto-generated />
using System;
using BetTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BetTracker.Data.Migrations
{
    [DbContext(typeof(BetTrackerContext))]
    [Migration("20260506193736_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.26");

            modelBuilder.Entity("BetTracker.Core.Models.Bookmaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Actif")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateActivation")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlLogo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Bookmakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Betclic",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 2,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Winamax",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 3,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Unibet",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 4,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "PMU",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 5,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Bwin",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 6,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "NetBet",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 7,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "ZEbet",
                            UrlLogo = ""
                        },
                        new
                        {
                            Id = 8,
                            Actif = false,
                            DateActivation = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nom = "Parions Sport",
                            UrlLogo = ""
                        });
                });

            modelBuilder.Entity("BetTracker.Core.Models.Calcul", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CoteBook1")
                        .HasColumnType("real");

                    b.Property<decimal>("CoteBook2")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateCalcul")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EVNette")
                        .HasColumnType("real");

                    b.Property<bool>("GoNoGo")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MiseBook1")
                        .HasColumnType("real");

                    b.Property<decimal>("MiseBook2")
                        .HasColumnType("real");

                    b.Property<int>("OffreId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PerteCouverture")
                        .HasColumnType("real");

                    b.Property<bool>("Valide")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OffreId");

                    b.ToTable("Calculs");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Execution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CalculId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CoteReelleBook1")
                        .HasColumnType("real");

                    b.Property<decimal>("CoteReelleBook2")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateExecution")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EVReelle")
                        .HasColumnType("real");

                    b.Property<decimal>("GainBrut")
                        .HasColumnType("real");

                    b.Property<decimal>("MiseReelleBook1")
                        .HasColumnType("real");

                    b.Property<decimal>("MiseReelleBook2")
                        .HasColumnType("real");

                    b.Property<int>("ResultatMatch")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CalculId")
                        .IsUnique();

                    b.ToTable("Executions");
                });

            modelBuilder.Entity("BetTracker.Core.Models.MouvementBankroll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookmakerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Montant")
                        .HasColumnType("real");

                    b.Property<int?>("OffreId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookmakerId");

                    b.HasIndex("OffreId");

                    b.ToTable("Mouvements");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Offre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BookmakerId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CoteMinimum")
                        .HasColumnType("real");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTerminaison")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MontantBonus")
                        .HasColumnType("real");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BookmakerId");

                    b.ToTable("Offres");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Calcul", b =>
                {
                    b.HasOne("BetTracker.Core.Models.Offre", "Offre")
                        .WithMany("Calculs")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Execution", b =>
                {
                    b.HasOne("BetTracker.Core.Models.Calcul", "Calcul")
                        .WithOne("Execution")
                        .HasForeignKey("BetTracker.Core.Models.Execution", "CalculId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calcul");
                });

            modelBuilder.Entity("BetTracker.Core.Models.MouvementBankroll", b =>
                {
                    b.HasOne("BetTracker.Core.Models.Bookmaker", "Bookmaker")
                        .WithMany("Mouvements")
                        .HasForeignKey("BookmakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BetTracker.Core.Models.Offre", "Offre")
                        .WithMany("Mouvements")
                        .HasForeignKey("OffreId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bookmaker");

                    b.Navigation("Offre");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Offre", b =>
                {
                    b.HasOne("BetTracker.Core.Models.Bookmaker", "Bookmaker")
                        .WithMany("Offres")
                        .HasForeignKey("BookmakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bookmaker");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Bookmaker", b =>
                {
                    b.Navigation("Mouvements");

                    b.Navigation("Offres");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Calcul", b =>
                {
                    b.Navigation("Execution");
                });

            modelBuilder.Entity("BetTracker.Core.Models.Offre", b =>
                {
                    b.Navigation("Calculs");

                    b.Navigation("Mouvements");
                });
#pragma warning restore 612, 618
        }
    }
}
